### ISSUE TITLE
attention_mask有bug

### ISSUE THREAD

**Issue by quzx** [ssbuild/qwen_finetuning#16]
data_utils.py这个处理，和千问finetune.py  不一致
151        for i,seqlen in enumerate(seqlens):
152            attention_mask[i,:seqlen] = 1

下面是千问官网的（github)  finetune.py
174  attention_mask=input_ids.ne(tokenizer.pad_token_id),

**Comment by ssbuild** [comment]
一样的，你再品品。

**Comment by quzx** [comment]
174 attention_mask=input_ids.ne(tokenizer.pad_token_id),    是非填充为1，填充符号为0
151 for i,seqlen in enumerate(seqlens):
152 attention_mask[i,:seqlen] = 1  是有效token都是对应1，后面扩充到MAX_INPUT_LENGTH的时候，用0填充；  是这个意思吗？

**Comment by quzx** [comment]
改正一下，上面的应该是  扩充到max_seq_length
谢谢，还望讲解一下

**Comment by ssbuild** [comment]
填充部分在后面，跟我写这个效果一样的

**Comment by quzx** [comment]
"非填充部分在后面" 没有理解这一句，   qwen的非填充在左边，填充在右边

**Comment by quzx** [comment]
你说的“在后面”是指在后续的程序中处理，还是指 你在左边填充？

**Comment by ssbuild** [comment]
> 你说的“在后面”是指在后续的程序中处理，还是指 你在左边填充？

口误，右填充
