### ISSUE TITLE
请教关于<|endoftext|>的问题

### ISSUE THREAD

**Issue by quzx** [ssbuild/qwen_finetuning#17]
aigc_zoo/src/aigc_zoo/model_zoo/qwen/tokenization_qwen.py  用到了  ENDOFTEXT = "<|endoftext|>"

**Comment by quzx** [comment]
不好意思，敲错了。继续写：
qwen的模型配置文件中也定义了"eos_token_id": 151643,
data_processor.py
83    elif chat_format == "raw":
84        raw_text = query
85        context_tokens = tokenizer.encode(raw_text)
如果待处理的不是问答SFT数据，而是原始文本，为什么这里不加eos ?

**Comment by ssbuild** [comment]
tokenizer.encode 默认开了add_special_tokens ， 会自动加上

**Comment by quzx** [comment]
好的，谢谢。那我把程序微调一下，那是不是就可以把预训练和SFT一起炖了？

**Comment by quzx** [comment]
预训练和SFT同时进行

**Comment by ssbuild** [comment]
> 预训练和SFT同时进行

分开搞吧，

**Comment by quzx** [comment]
ssbuild是很nice的项目，是真的适配了各个模型 👍
