### ISSUE TITLE
当batchsize>1 显示shape '[batchsize, -1]' is invalid for input of attention_mask size 

### ISSUE THREAD

**Issue by xxll88** [ssbuild/qwen_finetuning#2]
lora微调时,batchesize=2, 显示:
  File "/opt/conda/lib/python3.10/site-packages/deep_training/nlp/models/qwen/modeling_qwen.py", line 718, in forward
    attention_mask = attention_mask.view(batch_size, -1)
RuntimeError: shape '[2, -1]' is invalid for input of size 3969

经测：只有batchsize=1才能运行，>1时候，每个样本attention_mask都不同，就出错 shape '[batchsize, -1]' is invalid for input of size

问题似乎出在attention_mask的形状与期望的batch_size和样本数量之间的不匹配上。

**Comment by ssbuild** [comment]
[fixed](https://github.com/ssbuild/qwen_finetuning/blob/15f9717cb32a3f083d53ef42688b12b208c85935/data_utils.py#L117)

yes , fixed.
