### ISSUE TITLE
int4量化模型transformers使用报错

### ISSUE THREAD

**Issue by yxk9810** [ssbuild/qwen_finetuning#3]
![image](https://github.com/ssbuild/qwen_finetuning/assets/5186505/c8be7c36-8052-4cba-9990-d8604805203b)

**Comment by ssbuild** [comment]
参考 https://github.com/ssbuild/qwen_finetuning/blob/dev/infer.py
加载和推理

**Comment by yxk9810** [comment]
这个还需要安装aigc_zoo呀，有没有纯净点的，使用transformers就可以推理？
