### ISSUE TITLE
重新拉取了最新的Qwen-chat的所有模型和配置，以及本项目的最新代码，无法进行lora微调了

### ISSUE THREAD

**Issue by troycjj** [ssbuild/qwen_finetuning#5]
![image](https://github.com/ssbuild/qwen_finetuning/assets/52953954/a6f21e1d-1866-40df-8cbc-b6373f7f232c)

没有动过任何项目配置和模型配置

**Comment by troycjj** [comment]
torch==2.0.1
transformers==4.31.0
 NVIDIA-SMI 525.60.13    Driver Version: 525.60.13    CUDA Version: 12.0 
A40 48G

**Comment by ssbuild** [comment]
fixed , 训练精度问题，具体参见train.py

**Comment by troycjj** [comment]
训练时需要将模型的flash_attn关了，不然会提示需要A100/H100才能跑，关了就可以跑了
flash_attn=“auto”
![image](https://github.com/ssbuild/qwen_finetuning/assets/52953954/3744399f-6e2d-4d9a-9760-1cfb2b00e56d)

flash_attn=False 就OK了
