### ISSUE TITLE
NN_DataHelper

### ISSUE THREAD

**Issue by wellcasa** [ssbuild/qwen_finetuning#8]
NN_DataHelper 在make_dataset_all 会将数据tokenizer化，然后保存

1.make_dataset_all过程能不能将保存的名字和输入的文件名字一致是否可以?
2.处理完后，是否后面每次可以直接用，不用每次都tokennizer化。

**Comment by wellcasa** [comment]
我理解就是在这里 dataHelper.train_files把处理完的数据放在这里。但是就是名字都是你重新写的，不知道怎么对应
   train_datasets = dataHelper.load_distributed_random_sampler(
        dataHelper.train_files,
        with_load_memory=data_args.data_backend == 'record',
        collate_fn=dataHelper.collate_fn,
        batch_size=training_args.train_batch_size,
        drop_last=True,  # 多卡建议扔掉
        num_processes=trainer.world_size, process_index=trainer.global_rank,
        dataset_loader_filter_fn=dataset_loader_filter_fn,
        num_workers=0
    )

**Comment by ssbuild** [comment]
make_dataset_all 将文本数据制作特征数据。
train_datasets = dataHelper.load_distributed_random_sampler 就是分布式加载训练数据。
 你的问题是什么？

**Comment by wellcasa** [comment]
每次训练都做特征数据，比较麻烦，我想做一次，后面就用就好。直接加载用。

**Comment by ssbuild** [comment]
make_dataset_all 制作数据就会在对应的output文件夹有缓存 ， 不是每次训练都会制作数据 除非手动删除output下面的缓存文件。

https://github.com/ssbuild/numpy_io/blob/03c1e196f37935317e6ec29bbfad1f37e10c933d/src/numpy_io/pytorch_loader/data_helper.py#L168
